---
"extends":
  - "prettier-standard"
"parserOptions":
  "ecmaFeatures": 
    "jsx": true
"rules":
  "react/jsx-uses-react": "error"
  "react/jsx-uses-vars": "error"
  "import/no-webpack-loader-syntax": "off"
"plugins":
  - "eslint-plugin-react"
